version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "cargo"
    directory: "backend/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
